name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: document.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: document.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}